const DB_KEY="waslni_v1_db";const SESSION="waslni_v1_session";
function db(){return JSON.parse(localStorage.getItem(DB_KEY)||'{"customers":[],"captains":[],"rides":[]}')}
function save(d){localStorage.setItem(DB_KEY,JSON.stringify(d))}
function toast(t){const x=document.getElementById("toast");x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",2200)}
function hideAll(){document.querySelectorAll(".screen").forEach(x=>x.classList.add("hidden"))}
function goHome(){hideAll();document.getElementById("landing").classList.remove("hidden");document.getElementById("userBadge").classList.add("hidden")}
function showAuth(mode){hideAll();document.getElementById("auth").classList.remove("hidden");const c=document.getElementById("authContent");c.innerHTML=mode==="login"?`
<h2>تسجيل الدخول</h2><p class="muted">ادخل برقم الهاتف وكلمة المرور.</p>
<label>رقم الهاتف</label><input id="loginPhone" placeholder="07xxxxxxxxx">
<label>كلمة المرور</label><input id="loginPass" type="password" placeholder="••••••">
<button class="primary full" onclick="login()">دخول</button>
<button class="link-btn full" onclick="showAuth('register')">إنشاء حساب جديد</button>
<hr><button class="secondary full" onclick="adminLogin()">دخول الإدارة التجريبي</button>`:`
<h2>إنشاء حساب زبون</h2><p class="muted">حسابك يتيح لك طلب سيارة ومتابعة الرحلات.</p>
<label>الاسم</label><input id="regName" placeholder="اسمك">
<label>رقم الهاتف</label><input id="regPhone" placeholder="07xxxxxxxxx">
<label>كلمة المرور</label><input id="regPass" type="password" placeholder="••••••">
<button class="primary full" onclick="registerCustomer()">إنشاء الحساب</button>
<button class="link-btn full" onclick="showAuth('login')">لدي حساب بالفعل</button>`}
function registerCustomer(){const name=regName.value.trim(),phone=regPhone.value.trim(),pass=regPass.value;if(!name||!phone||pass.length<4)return toast("أكمل البيانات بشكل صحيح");const d=db();if(d.customers.some(x=>x.phone===phone))return toast("رقم الهاتف مسجل مسبقاً");d.customers.push({id:Date.now(),name,phone,pass});save(d);sessionStorage.setItem(SESSION,JSON.stringify({role:"customer",phone}));showCustomer()}
function login(){const phone=loginPhone.value.trim(),pass=loginPass.value,d=db();const u=d.customers.find(x=>x.phone===phone&&x.pass===pass);if(u){sessionStorage.setItem(SESSION,JSON.stringify({role:"customer",phone}));return showCustomer()}const c=d.captains.find(x=>x.phone===phone&&x.pass===pass);if(c){if(c.status==="pending")return showPending();if(c.status==="approved")return toast("تم تفعيلك — واجهة الكابتن ستكون بالنسخة القادمة");if(c.status==="rejected")return toast("تم رفض الطلب: "+(c.reason||"راجع الإدارة"))}toast("رقم الهاتف أو كلمة المرور غير صحيحة")}
function showCaptainRegister(){hideAll();document.getElementById("captainRegister").classList.remove("hidden")}
function submitCaptain(){const ids=["capName","capPhone","capDob","capArea","capCar","capModel","capColor","capPlate"];if(ids.some(id=>!document.getElementById(id).value.trim()))return toast("أكمل جميع بيانات الكابتن");const d=db(),phone=capPhone.value.trim();if(d.captains.some(x=>x.phone===phone))return toast("يوجد طلب بهذا الرقم");const docs={photo:capPhoto.files[0]?.name||"",id:capId.files[0]?.name||"",license:capLicense.files[0]?.name||"",reg:capReg.files[0]?.name||""};d.captains.push({id:Date.now(),name:capName.value.trim(),phone,dob:capDob.value,area:capArea.value.trim(),car:capCar.value.trim(),model:capModel.value.trim(),color:capColor.value.trim(),plate:capPlate.value.trim(),docs,status:"pending",createdAt:new Date().toISOString(),pass:"0000"});save(d);sessionStorage.setItem(SESSION,JSON.stringify({role:"captain",phone}));showPending()}
function showPending(){hideAll();document.getElementById("pending").classList.remove("hidden")}
function showCustomer(){hideAll();document.getElementById("customerApp").classList.remove("hidden");const s=JSON.parse(sessionStorage.getItem(SESSION));const u=db().customers.find(x=>x.phone===s.phone);document.getElementById("customerHello").textContent="مرحباً "+u.name+" 👋";document.getElementById("userBadge").textContent=u.name;document.getElementById("userBadge").classList.remove("hidden")}
function requestRide(){if(!destination.value.trim())return toast("اكتب الوجهة أولاً");const d=db(),s=JSON.parse(sessionStorage.getItem(SESSION));d.rides.push({id:Date.now(),customer:s.phone,pickup:pickup.value,destination:destination.value,status:"searching",createdAt:new Date().toISOString()});save(d);document.getElementById("rideStatus").classList.remove("hidden");document.getElementById("rideStatus").innerHTML="<h3>🔎 جارٍ البحث عن كابتن</h3><p>تم إرسال طلبك للكباتن القريبين. هذا نموذج أولي، وسيتم ربط الطلبات الحقيقية في المرحلة التالية.</p>";toast("تم إرسال الطلب")}
destination.addEventListener("input",()=>{const has=destination.value.trim();distance.textContent=has?"4.2 كم":"—";fare.textContent=has?"5,000 د.ع":"—"});
function adminLogin(){const p=prompt("اسم المستخدم:");const q=prompt("كلمة المرور:");if(p==="admin"&&q==="1234"){sessionStorage.setItem(SESSION,JSON.stringify({role:"admin"}));renderAdmin()}else toast("بيانات الإدارة غير صحيحة")}
function renderAdmin(){hideAll();document.getElementById("admin").classList.remove("hidden");const d=db();sCustomers.textContent=d.customers.length;sCaptains.textContent=d.captains.length;sPending.textContent=d.captains.filter(x=>x.status==="pending").length;sActive.textContent=d.captains.filter(x=>x.status==="approved").length;const list=document.getElementById("captainList");if(!d.captains.length){list.innerHTML='<p class="muted">لا توجد طلبات حالياً.</p>';return}list.innerHTML=d.captains.map(c=>`<div class="captain-item"><div class="captain-row"><b>${esc(c.name)}</b><span class="tag ${c.status==="approved"?"active":""}">${c.status==="pending"?"قيد المراجعة":c.status==="approved"?"مفعل":"مرفوض"}</span></div><div class="info"><span>📞 ${esc(c.phone)}</span><span>🚕 ${esc(c.car)} — ${esc(c.model)}</span><span>🎨 ${esc(c.color)}</span><span>🔢 اللوحة: ${esc(c.plate)}</span><span>📍 ${esc(c.area)}</span><span>📄 المستمسكات: ${Object.values(c.docs).filter(Boolean).length}/4</span></div>${c.status==="pending"?`<div class="captain-actions"><button class="primary" onclick="approve(${c.id})">✓ قبول وتفعيل</button><button class="secondary danger" onclick="rejectCaptain(${c.id})">رفض</button></div>`:""}</div>`).join("")}
function approve(id){const d=db(),c=d.captains.find(x=>x.id===id);c.status="approved";c.approvedAt=new Date().toISOString();save(d);renderAdmin();toast("تم قبول وتفعيل الكابتن")}
function rejectCaptain(id){const reason=prompt("سبب الرفض:","المستمسكات غير واضحة");if(reason===null)return;const d=db(),c=d.captains.find(x=>x.id===id);c.status="rejected";c.reason=reason;save(d);renderAdmin();toast("تم رفض الطلب")}
function logout(){sessionStorage.removeItem(SESSION);goHome()}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
window.addEventListener("load",()=>{const s=sessionStorage.getItem(SESSION);if(s){const x=JSON.parse(s);if(x.role==="admin")renderAdmin();else if(x.role==="customer")showCustomer();else if(x.role==="captain")showPending()}})
